#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bibtex
Version  : 0.5.1
Release  : 58
URL      : https://cran.r-project.org/src/contrib/bibtex_0.5.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bibtex_0.5.1.tar.gz
Summary  : Bibtex Parser
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-backports
BuildRequires : R-backports
BuildRequires : buildreq-R

%description
# bibtex
<!-- badges: start -->
[![CRAN](https://www.r-pkg.org/badges/version/bibtex)](https://CRAN.R-project.org/package=bibtex)
[![R-CMD-check](https://github.com/ropensci/bibtex/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/ropensci/bibtex/actions/workflows/R-CMD-check.yaml)
[![Coverage](https://codecov.io/github/ropensci/bibtex/coverage.svg?branch=master)](https://codecov.io/gh/ropensci/bibtex/branch/master)
[![Downloads](https://cranlogs.r-pkg.org/badges/bibtex)](https://cran.r-project.org/package=bibtex)
[![Total Downloads](https://cranlogs.r-pkg.org/badges/grand-total/bibtex?color=blue)](https://cran.r-project.org/package=bibtex)
<!-- badges: end -->

%prep
%setup -q -n bibtex
cd %{_builddir}/bibtex

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678811317

%install
export SOURCE_DATE_EPOCH=1678811317
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bibtex/DESCRIPTION
/usr/lib64/R/library/bibtex/INDEX
/usr/lib64/R/library/bibtex/Meta/Rd.rds
/usr/lib64/R/library/bibtex/Meta/features.rds
/usr/lib64/R/library/bibtex/Meta/hsearch.rds
/usr/lib64/R/library/bibtex/Meta/links.rds
/usr/lib64/R/library/bibtex/Meta/nsInfo.rds
/usr/lib64/R/library/bibtex/Meta/package.rds
/usr/lib64/R/library/bibtex/NAMESPACE
/usr/lib64/R/library/bibtex/NEWS.Rd
/usr/lib64/R/library/bibtex/NEWS.md
/usr/lib64/R/library/bibtex/R/bibtex
/usr/lib64/R/library/bibtex/R/bibtex.rdb
/usr/lib64/R/library/bibtex/R/bibtex.rdx
/usr/lib64/R/library/bibtex/REFERENCES.bib
/usr/lib64/R/library/bibtex/bib/badFormat.bib
/usr/lib64/R/library/bibtex/bib/base.bib
/usr/lib64/R/library/bibtex/bib/datasets.bib
/usr/lib64/R/library/bibtex/bib/grDevices.bib
/usr/lib64/R/library/bibtex/bib/graphics.bib
/usr/lib64/R/library/bibtex/bib/issue15.bib
/usr/lib64/R/library/bibtex/bib/issue17.bib
/usr/lib64/R/library/bibtex/bib/issue18.bib
/usr/lib64/R/library/bibtex/bib/issue23.bib
/usr/lib64/R/library/bibtex/bib/issue6.bib
/usr/lib64/R/library/bibtex/bib/issue7.bib
/usr/lib64/R/library/bibtex/bib/issue9.bib
/usr/lib64/R/library/bibtex/bib/methods.bib
/usr/lib64/R/library/bibtex/bib/multiline_string.bib
/usr/lib64/R/library/bibtex/bib/stats.bib
/usr/lib64/R/library/bibtex/bib/stats4.bib
/usr/lib64/R/library/bibtex/bib/tools.bib
/usr/lib64/R/library/bibtex/bib/unable_recover_42.bib
/usr/lib64/R/library/bibtex/bib/unbalanced_braces.bib
/usr/lib64/R/library/bibtex/bib/utils.bib
/usr/lib64/R/library/bibtex/bib/xampl_message.bib
/usr/lib64/R/library/bibtex/bib/xampl_mod.bib
/usr/lib64/R/library/bibtex/bib/xampl_multiline.bib
/usr/lib64/R/library/bibtex/bib/xampl_preamble.bib
/usr/lib64/R/library/bibtex/bib/xampl_single.bib
/usr/lib64/R/library/bibtex/bib/xampl_standard.bib
/usr/lib64/R/library/bibtex/help/AnIndex
/usr/lib64/R/library/bibtex/help/aliases.rds
/usr/lib64/R/library/bibtex/help/bibtex.rdb
/usr/lib64/R/library/bibtex/help/bibtex.rdx
/usr/lib64/R/library/bibtex/help/paths.rds
/usr/lib64/R/library/bibtex/html/00Index.html
/usr/lib64/R/library/bibtex/html/R.css
/usr/lib64/R/library/bibtex/tests/testthat.R
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/authors.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/do_read_bib.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/examples.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/full_xampl.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/multiline.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/preamble.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/previous-issues.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/previous-issues/issue9.bib
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/read.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/standard-entries.md
/usr/lib64/R/library/bibtex/tests/testthat/_snaps/utils.md
/usr/lib64/R/library/bibtex/tests/testthat/test-authors.R
/usr/lib64/R/library/bibtex/tests/testthat/test-bibtex.R
/usr/lib64/R/library/bibtex/tests/testthat/test-deprecated.R
/usr/lib64/R/library/bibtex/tests/testthat/test-do_read_bib.R
/usr/lib64/R/library/bibtex/tests/testthat/test-examples.R
/usr/lib64/R/library/bibtex/tests/testthat/test-fatal-errors.R
/usr/lib64/R/library/bibtex/tests/testthat/test-full_xampl.R
/usr/lib64/R/library/bibtex/tests/testthat/test-multiline.R
/usr/lib64/R/library/bibtex/tests/testthat/test-preamble.R
/usr/lib64/R/library/bibtex/tests/testthat/test-previous-issues.R
/usr/lib64/R/library/bibtex/tests/testthat/test-read.R
/usr/lib64/R/library/bibtex/tests/testthat/test-standard-entries.R
/usr/lib64/R/library/bibtex/tests/testthat/test-utils.R
/usr/lib64/R/library/bibtex/tests/testthat/test-write.R
